//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birth_Certificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Birth_Certificate()
        {
            this.Identification_Card = new HashSet<Identification_Card>();
            this.Passports = new HashSet<Passport>();
        }
    
        public int ID_Born { get; set; }
        public string ID_Number_Born { get; set; }
        public string Born_name { get; set; }
        public string Father_name { get; set; }
        public string Mother_name { get; set; }
        public string Grand_last_name { get; set; }
        public string Gendar_Born { get; set; }
        public string Nationality { get; set; }
        public string Religion_Father { get; set; }
        public string Occupation_Father { get; set; }
        public string Nationality_Father { get; set; }
        public string Address { get; set; }
        public System.DateTime Birth_date { get; set; }
        public System.DateTime Release_date { get; set; }
        public string Birth_place { get; set; }
        public string Religion_Mother { get; set; }
        public string Occupation_Mother { get; set; }
        public string Nationality_Mother { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Identification_Card> Identification_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passport> Passports { get; set; }
    }
}
