//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identification_Card
    {
        public int ID_Card { get; set; }
        public string ID_Number { get; set; }
        public string Quadruple_Name { get; set; }
        public string Blood_Type { get; set; }
        public byte[] Personal_Picture { get; set; }
        public System.DateTime Release_Date { get; set; }
        public int ID_Born { get; set; }
        public System.DateTime End_Date { get; set; }
    
        public virtual Birth_Certificate Birth_Certificate { get; set; }
    }
}
