//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Civil_statusEntities1 : DbContext
    {
        public Civil_statusEntities1()
            : base("name=Civil_statusEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birth_Certificate> Birth_Certificates { get; set; }
        public virtual DbSet<Identification_Card> Identification_Cards { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
    }
}
