//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int ID { get; set; }
        public string ID_Passport_Number { get; set; }
        public string The_Third_Name { get; set; }
        public string Nickname { get; set; }
        public string Occupation { get; set; }
        public System.DateTime Release_date { get; set; }
        public byte[] Personal_Picture { get; set; }
        public int ID_Born { get; set; }
        public System.DateTime End_Date { get; set; }
    
        public virtual Birth_Certificate Birth_Certificate { get; set; }
    }
}
